import { DEG, INCH } from '../math/MathUtil.js';
import { MOTOR_PRESETS, DEFAULT_MOTOR_ID, GOBILDA_GEARBOXES } from './presets/motors.js';
import { LAYOUT_LABELS } from '../drivetrain/layouts.js';
import {
  ROSTER_SLOTS,
  ARCHETYPE_OPTIONS,
  QUALITY_OPTIONS,
  SKILL_OPTIONS,
} from '../ai/roster.js';
import { LAUNCH_SYSTEM_OPTIONS } from '../robot/biobuzz/launchSystems.js';

/**
 * The single source of truth for every tunable in the simulator.
 *
 * Each parameter carries its type, range, unit, default and a plain-English
 * explanation of what it changes. The parameter panel is generated from this
 * list, so adding a tunable is one entry here and nothing else -- no UI code,
 * no serialisation code, no defaults duplicated in three places.
 *
 * Values are stored in SI. `display` names the unit shown in the UI.
 *
 * @module
 */

/**
 * @typedef {object} ParamDef
 * @property {string} path         dotted path into the config object
 * @property {string} label
 * @property {'number'|'enum'|'boolean'} type
 * @property {any} default
 * @property {string} [help]
 * @property {number} [min]
 * @property {number} [max]
 * @property {number} [step]
 * @property {string} [unit]       SI unit the value is stored in
 * @property {string} [display]    unit shown in the UI (value is converted into it)
 * @property {string} [suffix]     label shown after the value when it is *already*
 *                                 stored in that unit, so no conversion happens.
 *                                 Use this rather than `unit` for the handful of
 *                                 values kept in non-SI form (RPM, milliseconds,
 *                                 degrees per second) because the code that
 *                                 consumes them expects those units.
 * @property {{value:any,label:string}[]} [options]
 * @property {boolean} [advanced]  hidden until "show advanced" is enabled
 * @property {boolean} [rebuild]   changing this requires rebuilding the drivetrain
 */

/**
 * @typedef {object} ParamGroup
 * @property {string} id
 * @property {string} label
 * @property {string} description
 * @property {ParamDef[]} params
 */

const motorOptions = Object.values(MOTOR_PRESETS).map((m) => ({ value: m.id, label: m.name }));
const gearboxOptions = GOBILDA_GEARBOXES.map((g) => ({ value: g.ratio, label: g.label }));
const layoutOptions = Object.entries(LAYOUT_LABELS).map(([value, label]) => ({ value, label }));

/**
 * Parameters for one AI slot.
 *
 * Generated rather than written out three times, so the partner and the two
 * opponents cannot drift apart -- and because they genuinely are the same
 * question asked three times. A partner who cannot shoot is every bit as much
 * a thing to practise around as an opponent who can; arguably more, since you
 * cannot push your partner out of the way.
 */
function rosterParams(slot) {
  const { id, label, help } = slot;
  return [
    {
      path: `ai.${id}.enabled`,
      label: `${label}: on the field`,
      type: 'boolean',
      default: true,
      help,
    },
    {
      path: `ai.${id}.archetype`,
      label: `${label}: robot`,
      type: 'enum',
      options: ARCHETYPE_OPTIONS,
      default: 'random',
      help: 'What the machine is, and specifically what it can score with. A CELL has to be LAUNCHED into and a FLOWER has to be placed into by hand (G419), so a robot built for one cannot do the other -- and a pushbot does neither.',
    },
    {
      path: `ai.${id}.quality`,
      label: `${label}: build`,
      type: 'enum',
      options: QUALITY_OPTIONS,
      default: 'random',
      help: 'How well it is built: motors on the flywheel, how repeatable the hood is, how often the intake jams. The same robot at two build standards scores twice as much.',
    },
    {
      path: `ai.${id}.skill`,
      label: `${label}: driver`,
      type: 'enum',
      options: SKILL_OPTIONS,
      default: 'random',
      help: 'The human: reaction time, precision, how much power they dare use, how often they commit to something unhelpful.',
    },
  ];
}

/** @type {ParamGroup[]} */
export const SCHEMA = [
  {
    id: 'drivetrain',
    label: 'Drivetrain',
    description:
      'Wheel layout and geometry. The default is a parallel-plate mecanum chassis on 96 mm wheels, the most common FTC configuration.',
    params: [
      {
        path: 'drivetrain.type',
        label: 'Drivetrain type',
        type: 'enum',
        options: layoutOptions,
        default: 'mecanum',
        rebuild: true,
        help: 'Mecanum and X-drive can strafe; tank cannot. Tank has ~30% more forward grip because its wheels put force straight down the robot rather than along a 45 degree roller.',
      },
      {
        path: 'drivetrain.wheelbase',
        label: 'Wheelbase',
        type: 'number',
        default: 0.3239,
        min: 0.08,
        max: 0.44,
        step: 0.001,
        unit: 'm',
        display: 'in',
        rebuild: true,
        help: 'Front axle to rear axle. A longer wheelbase resists spinning out but turns more reluctantly.',
      },
      {
        path: 'drivetrain.trackWidth',
        label: 'Track width',
        type: 'number',
        default: 0.3556,
        min: 0.08,
        max: 0.44,
        step: 0.001,
        unit: 'm',
        display: 'in',
        rebuild: true,
        help: 'Left wheel centre to right wheel centre. Wider is more stable against tipping and gives more turning leverage.',
      },
      {
        path: 'drivetrain.wheelRadius',
        label: 'Wheel radius',
        type: 'number',
        default: 0.048,
        min: 0.02,
        max: 0.09,
        step: 0.0005,
        unit: 'm',
        display: 'mm',
        rebuild: true,
        help: '48 mm = a 96 mm goBILDA mecanum wheel. Bigger wheels raise top speed and lower acceleration for the same gearing.',
      },
      {
        path: 'drivetrain.wheelMass',
        label: 'Wheel mass',
        type: 'number',
        default: 0.32,
        min: 0.05,
        max: 1.2,
        step: 0.01,
        unit: 'kg',
        display: 'kg',
        advanced: true,
        rebuild: true,
        help: 'Sets how much of the motor torque is spent spinning the wheel up rather than moving the robot. Usually small next to the reflected rotor inertia.',
      },
      {
        path: 'drivetrain.rollerAngle',
        label: 'Mecanum roller angle',
        type: 'number',
        default: 45 * DEG,
        min: 20 * DEG,
        max: 70 * DEG,
        step: DEG,
        unit: 'rad',
        display: 'deg',
        advanced: true,
        rebuild: true,
        help: 'Standard mecanum wheels use 45 degrees. Lower angles trade strafing authority for forward grip.',
      },
    ],
  },

  {
    id: 'chassis',
    label: 'Chassis & mass',
    description:
      'Mass properties. These decide how the robot accelerates, how quickly it rotates, and how much weight transfers off the front wheels when the driver slams forward.',
    params: [
      {
        path: 'chassis.mass',
        label: 'Robot mass',
        type: 'number',
        default: 15,
        min: 3,
        max: 30,
        step: 0.1,
        unit: 'kg',
        display: 'kg',
        help: 'Total mass including battery and mechanisms. The FTC limit is 42 lb (19.05 kg); a drivetrain-only chassis is usually 8-12 kg.',
      },
      {
        path: 'chassis.length',
        label: 'Frame length',
        type: 'number',
        default: 0.4318,
        min: 0.15,
        max: 0.46,
        step: 0.001,
        unit: 'm',
        display: 'in',
        help: 'Used for collisions and for the default moment of inertia. 17 in leaves a little room inside the 18 in sizing cube.',
      },
      {
        path: 'chassis.width',
        label: 'Frame width',
        type: 'number',
        default: 0.4064,
        min: 0.15,
        max: 0.46,
        step: 0.001,
        unit: 'm',
        display: 'in',
        help: 'Outside width across the side plates.',
      },
      {
        path: 'chassis.height',
        label: 'Frame height',
        type: 'number',
        default: 0.18,
        min: 0.05,
        max: 0.46,
        step: 0.005,
        unit: 'm',
        display: 'in',
        help: 'Visual only for now; a future mechanism model will use it.',
      },
      {
        path: 'chassis.autoInertia',
        label: 'Auto moment of inertia',
        type: 'boolean',
        default: true,
        help: 'Estimates rotational inertia from mass and frame size as a uniform slab, then applies the concentration factor below.',
      },
      {
        path: 'chassis.inertiaFactor',
        label: 'Inertia concentration factor',
        type: 'number',
        default: 1.25,
        min: 0.6,
        max: 2.5,
        step: 0.01,
        advanced: true,
        help: 'Real robots carry mass at the perimeter (motors, plates, battery), so their rotational inertia runs 10-40% above a uniform slab. Raise this if the simulated robot spins up faster than yours.',
      },
      {
        path: 'chassis.momentOfInertia',
        label: 'Moment of inertia (manual)',
        type: 'number',
        default: 0.4,
        min: 0.05,
        max: 3,
        step: 0.01,
        unit: 'kg*m^2',
        advanced: true,
        help: 'Used only when auto is off. Measure it by timing your robot through a known rotation at known power.',
      },
      {
        path: 'chassis.cgHeight',
        label: 'CG height',
        type: 'number',
        default: 0.12,
        min: 0.02,
        max: 0.45,
        step: 0.005,
        unit: 'm',
        display: 'in',
        help: 'Height of the centre of gravity above the tiles. This alone controls how much weight transfers under acceleration, and how easily the robot tips when it hits a wall sideways.',
      },
      {
        path: 'chassis.cgOffsetX',
        label: 'CG offset (forward)',
        type: 'number',
        default: 0,
        min: -0.15,
        max: 0.15,
        step: 0.002,
        unit: 'm',
        display: 'in',
        help: 'Positive moves the CG toward the front. A nose-heavy robot pushes harder but has less rear grip when accelerating.',
      },
      {
        path: 'chassis.cgOffsetY',
        label: 'CG offset (left)',
        type: 'number',
        default: 0,
        min: -0.15,
        max: 0.15,
        step: 0.002,
        unit: 'm',
        display: 'in',
        help: 'Positive moves the CG to the robot\'s left. An off-centre battery makes the robot pull to one side at full power.',
      },
      {
        path: 'chassis.weightTransferFactor',
        label: 'Weight transfer factor',
        type: 'number',
        default: 1,
        min: 0,
        max: 1.5,
        step: 0.01,
        advanced: true,
        help: '1 is the rigid-body answer. Lower it to approximate a chassis that flexes, which spreads transfer out over time. Set to 0 to switch weight transfer off entirely and see how much it was affecting you.',
      },
    ],
  },

  {
    id: 'motor',
    label: 'Motors & gearing',
    description:
      'Motor curve and drivetrain reduction. Defaults describe a goBILDA Yellow Jacket at 19.2:1, the 312 RPM part that most mecanum chassis use.',
    params: [
      {
        path: 'motor.preset',
        label: 'Motor preset',
        type: 'enum',
        options: motorOptions,
        default: DEFAULT_MOTOR_ID,
        rebuild: true,
        help: 'Loads catalogue figures into the fields below. Editing any field afterwards is fine and is encouraged if you have measured your own motors.',
      },
      {
        path: 'motor.gearRatio',
        label: 'Gearbox ratio',
        type: 'number',
        default: 19.2,
        min: 1,
        max: 200,
        step: 0.1,
        rebuild: true,
        help: 'Motor revolutions per output revolution. Common goBILDA options: ' +
          gearboxOptions.map((g) => g.label).join(', ') + '.',
      },
      {
        path: 'motor.externalRatio',
        label: 'External reduction',
        type: 'number',
        default: 1,
        min: 0.2,
        max: 5,
        step: 0.01,
        advanced: true,
        rebuild: true,
        help: 'Any extra chain, belt or gear stage between the gearbox and the wheel. 1 for a direct-drive parallel-plate chassis.',
      },
      {
        path: 'motor.efficiency',
        label: 'Drivetrain efficiency',
        type: 'number',
        default: 0.8,
        min: 0.3,
        max: 1,
        step: 0.01,
        help: 'Fraction of motor torque that reaches the wheel. A multi-stage planetary plus a chain run is realistically 0.70-0.85. Assuming 1.0 is the most common reason a simulated robot out-accelerates the real one.',
      },
      {
        path: 'motor.freeSpeedRpm',
        label: 'Free speed (bare motor)',
        type: 'number',
        default: 6000,
        min: 1000,
        max: 20000,
        step: 10,
        suffix: 'rpm',
        advanced: true,
        rebuild: true,
        help: 'Motor shaft speed with no load at 12 V, before the gearbox.',
      },
      {
        path: 'motor.stallTorque',
        label: 'Stall torque (bare motor)',
        type: 'number',
        default: 0.126,
        min: 0.005,
        max: 1,
        step: 0.001,
        unit: 'N*m',
        advanced: true,
        rebuild: true,
        help: 'Torque at zero speed and 12 V, before the gearbox.',
      },
      {
        path: 'motor.stallCurrent',
        label: 'Stall current',
        type: 'number',
        default: 9.2,
        min: 1,
        max: 40,
        step: 0.1,
        unit: 'A',
        advanced: true,
        rebuild: true,
        help: 'Current at zero speed and 12 V. Sets the winding resistance, so it drives how hard the battery sags.',
      },
      {
        path: 'motor.freeCurrent',
        label: 'Free current',
        type: 'number',
        default: 0.25,
        min: 0,
        max: 5,
        step: 0.01,
        unit: 'A',
        advanced: true,
        rebuild: true,
        help: 'No-load current: the motor\'s own internal friction.',
      },
      {
        path: 'motor.ticksPerRev',
        label: 'Encoder ticks / motor rev',
        type: 'number',
        default: 28,
        min: 1,
        max: 4096,
        step: 1,
        advanced: true,
        rebuild: true,
        help: '28 for goBILDA, REV HD Hex and NeveRest motors (7 pulses in quadrature).',
      },
      {
        path: 'motor.rotorInertia',
        label: 'Rotor inertia',
        type: 'number',
        default: 7e-6,
        min: 1e-6,
        max: 1e-4,
        step: 1e-6,
        unit: 'kg*m^2',
        advanced: true,
        rebuild: true,
        help: 'Reflected through the gearbox this is multiplied by the ratio squared, so at 19.2:1 it adds around 5 kg of apparent mass to a 15 kg robot. No FTC vendor publishes it, so the default is a geometric estimate -- this is the knob to turn if the simulator accelerates differently from your real robot.',
      },
      {
        path: 'motor.staticFrictionTorque',
        label: 'Breakaway torque',
        type: 'number',
        default: 0.05,
        min: 0,
        max: 0.6,
        step: 0.005,
        unit: 'N*m',
        advanced: true,
        help: 'Torque needed at the wheel before the drivetrain moves at all. This is what you feel pushing a powered-off robot.',
      },
      {
        path: 'motor.viscousFriction',
        label: 'Viscous friction',
        type: 'number',
        default: 0.004,
        min: 0,
        max: 0.1,
        step: 0.0005,
        unit: 'N*m/(rad/s)',
        advanced: true,
        help: 'Speed-proportional drag in the gearbox and bearings.',
      },
    ],
  },

  {
    id: 'battery',
    label: 'Battery',
    description:
      'A 12 V FTC pack with real internal resistance. Motor current sags the bus, and because both speed and torque scale with voltage the robot gets slower and weaker exactly when it is working hardest.',
    params: [
      {
        path: 'battery.enabled',
        label: 'Simulate voltage sag',
        type: 'boolean',
        default: true,
        help: 'Turn off to hold the bus at a fixed voltage. Useful for isolating whether a handling problem is electrical or mechanical.',
      },
      {
        path: 'battery.openCircuitVoltage',
        label: 'Resting voltage (full)',
        type: 'number',
        default: 13.0,
        min: 9,
        max: 14,
        step: 0.05,
        unit: 'V',
        help: 'A freshly charged FTC pack sits a little above 13 V.',
      },
      {
        path: 'battery.internalResistance',
        label: 'Internal resistance',
        type: 'number',
        default: 0.03,
        min: 0.005,
        max: 0.2,
        step: 0.001,
        unit: 'ohm',
        help: 'The main knob for pack health. A new pack is around 0.02 ohm; a well-used one can be 0.05 or worse, which is several volts of sag at full current.',
      },
      {
        path: 'battery.startingStateOfCharge',
        label: 'Starting charge',
        type: 'number',
        default: 1,
        min: 0.05,
        max: 1,
        step: 0.01,
        help: 'Start a session part-drained to rehearse the last match of the day, when the pack is tired and the robot handles differently.',
      },
      {
        path: 'battery.capacityAmpHours',
        label: 'Pack capacity',
        type: 'number',
        default: 3,
        min: 0.5,
        max: 6,
        step: 0.1,
        unit: 'Ah',
        advanced: true,
        help: 'Standard FTC NiMH packs are 3000 mAh.',
      },
      {
        path: 'battery.baseLoadAmps',
        label: 'Base electrical load',
        type: 'number',
        default: 1.2,
        min: 0,
        max: 10,
        step: 0.1,
        unit: 'A',
        advanced: true,
        help: 'Control Hub, servos and sensors draw current before the drive motors do.',
      },
      {
        path: 'battery.nominalVoltage',
        label: 'Motor rating voltage',
        type: 'number',
        default: 12,
        min: 6,
        max: 24,
        step: 0.5,
        unit: 'V',
        advanced: true,
        rebuild: true,
        help: 'The voltage the motor catalogue figures were measured at. Leave at 12 for FTC.',
      },
    ],
  },

  {
    id: 'camera',
    label: 'Camera & AprilTags',
    description:
      'A webcam looking for the BIOBUZZ AprilTags. The clusters face downward off the underside of a CELL, so whether you can see one at all depends mostly on where the camera points -- which is the first thing to find out before building an AUTO around tag localisation.',
    params: [
      {
        path: 'camera.enabled',
        label: 'Camera fitted',
        type: 'boolean',
        default: true,
      },
      {
        path: 'camera.pitchDegrees',
        label: 'Camera pitch',
        type: 'number',
        default: 20,
        min: -30,
        max: 70,
        step: 1,
        suffix: 'deg',
        help: 'Up is positive. Pitched up by default, because the tags face downward off a raised CELL and a level camera sees almost nothing -- set it to 0 and watch the detections stop, which is worth doing once.',
      },
      {
        path: 'camera.yawDegrees',
        label: 'Camera yaw',
        type: 'number',
        default: 0,
        min: -180,
        max: 180,
        step: 1,
        suffix: 'deg',
        help: 'Counter-clockwise from straight ahead. A camera aimed sideways sees the tags while the robot drives at something else.',
      },
      {
        path: 'camera.x',
        label: 'Camera forward offset',
        type: 'number',
        default: 0.15,
        min: -0.3,
        max: 0.3,
        step: 0.005,
        unit: 'm',
        display: 'in',
        help: 'Where the lens is, in the robot frame. It matters: a pose fix gives you where the *camera* was, and this is what turns that into where the robot was.',
      },
      {
        path: 'camera.y',
        label: 'Camera left offset',
        type: 'number',
        default: 0,
        min: -0.3,
        max: 0.3,
        step: 0.005,
        unit: 'm',
        display: 'in',
      },
      {
        path: 'camera.z',
        label: 'Camera height',
        type: 'number',
        default: 0.25,
        min: 0.03,
        max: 0.45,
        step: 0.005,
        unit: 'm',
        display: 'in',
        help: 'Higher is a shallower look up at a raised CELL, which decodes better. G404 caps the ROBOT at 18 in to start with.',
      },
      {
        path: 'camera.fovDegrees',
        label: 'Field of view',
        type: 'number',
        default: 60,
        min: 20,
        max: 140,
        step: 1,
        suffix: 'deg',
        help: 'Horizontal. A Logitech C270 is about 60, a C920 about 70, a fisheye more. Wider sees more tags and makes each one smaller, which is the whole trade.',
      },
      {
        path: 'camera.latencyMs',
        label: 'Vision latency',
        type: 'number',
        default: 60,
        min: 0,
        max: 300,
        step: 5,
        suffix: 'ms',
        help: 'Exposure, transfer, decode and the processor thread. At 1 m/s, 60 ms is 6 cm of position error with a perfect tag reading, which is why a pose fix wants applying thoughtfully rather than every loop.',
      },
      {
        path: 'camera.frameRateHz',
        label: 'Frame rate',
        type: 'number',
        default: 30,
        min: 1,
        max: 120,
        step: 1,
        unit: 'Hz',
        help: 'A detection is up to one frame stale before the pipeline even starts.',
      },
      {
        path: 'camera.widthPixels',
        label: 'Resolution width',
        type: 'number',
        default: 640,
        min: 160,
        max: 1920,
        step: 16,
        advanced: true,
        help: 'Sets how many pixels wide a tag is at a given range, which is what decides whether it decodes. It is also what sets the vertical field of view, together with the height.',
      },
      {
        path: 'camera.heightPixels',
        label: 'Resolution height',
        type: 'number',
        default: 480,
        min: 120,
        max: 1080,
        step: 8,
        advanced: true,
      },
      {
        path: 'camera.minTagPixels',
        label: 'Minimum tag size',
        type: 'number',
        default: 14,
        min: 4,
        max: 60,
        step: 1,
        suffix: 'px',
        advanced: true,
        help: 'How wide a tag has to be on the sensor to decode. Below about a dozen pixels it is noise.',
      },
      {
        path: 'camera.maxIncidenceDegrees',
        label: 'Maximum view angle',
        type: 'number',
        default: 70,
        min: 20,
        max: 89,
        step: 1,
        suffix: 'deg',
        advanced: true,
        help: 'Off the tag\u2019s own normal. Past this it is too foreshortened to decode. The constraint that actually binds in BIOBUZZ, because the tags face the floor.',
      },
      {
        path: 'camera.rangeMax',
        label: 'Maximum range',
        type: 'number',
        default: 5,
        min: 0.5,
        max: 12,
        step: 0.1,
        unit: 'm',
        display: 'ft',
        advanced: true,
      },
      {
        path: 'camera.rangeNoise',
        label: 'Range noise',
        type: 'number',
        default: 0.02,
        min: 0,
        max: 0.2,
        step: 0.005,
        advanced: true,
        help: 'As a fraction of range. A couple of percent is realistic for a 3.25 in tag.',
      },
      {
        path: 'camera.bearingNoiseDegrees',
        label: 'Bearing noise',
        type: 'number',
        default: 0.5,
        min: 0,
        max: 10,
        step: 0.1,
        suffix: 'deg',
        advanced: true,
      },
    ],
  },

  {
    id: 'odometry',
    label: 'Odometry',
    description:
      'Dead-wheel pods and the board that turns them into a pose. A drive wheel slips and a pod does not, which is why teams bolt these on -- but the pose is an integral, so every calibration error is permanent rather than averaging out.',
    params: [
      {
        path: 'odometry.enabled',
        label: 'Odometry fitted',
        type: 'boolean',
        default: true,
        help: 'Whether the robot has pods at all. With them off, robot.odometry reports nothing and an AUTO has only the drive encoders and the IMU, which is the harder problem.',
      },
      {
        path: 'odometry.type',
        label: 'Setup',
        type: 'enum',
        options: [
          { value: 'twoPod', label: 'Two pods + IMU (Pinpoint, OTOS)' },
          { value: 'threePod', label: 'Three pods (heading from the pods)' },
        ],
        default: 'twoPod',
        help: 'Two pods take their heading from the IMU, which drifts. Three pods get it from the difference between two parallel pods, which does not drift but is only as good as the distance you measured between them.',
      },
      {
        path: 'odometry.yawScalar',
        label: 'Yaw scalar',
        type: 'number',
        default: 1,
        min: 0.9,
        max: 1.1,
        step: 0.001,
        help: 'A Pinpoint\u2019s one calibration knob. 1 is calibrated. Set it to 1.02 and four 90 degree turns leave the heading 7 degrees out, and every straight line after that goes the wrong way -- which is what a miscalibrated robot actually does.',
      },
      {
        path: 'odometry.lateralOffset',
        label: 'Forward pod, sideways offset',
        type: 'number',
        default: -0.08,
        min: -0.25,
        max: 0.25,
        step: 0.005,
        unit: 'm',
        display: 'in',
        help: 'How far the forward-measuring pod sits to the robot\u2019s left. Turning carries the pod sideways and the reading contains that motion, so this number is how it comes back out. Tell it the wrong one and turning in place moves the pose.',
      },
      {
        path: 'odometry.forwardOffset',
        label: 'Lateral pod, forward offset',
        type: 'number',
        default: 0.06,
        min: -0.25,
        max: 0.25,
        step: 0.005,
        unit: 'm',
        display: 'in',
        help: 'How far ahead of centre the sideways-measuring pod sits. Same job as the one above, for the other pod.',
      },
      {
        path: 'odometry.offsetError',
        label: 'Pod offset error',
        type: 'number',
        default: 0,
        min: -0.1,
        max: 0.1,
        step: 0.001,
        unit: 'm',
        display: 'in',
        help: 'How far the pods really are from where you told the board they are. Invisible driving in straight lines; set it to an inch and turning in place starts moving the pose, which is the odometry failure that looks like a drivetrain problem and is not.',
      },
      {
        path: 'odometry.trackWidth',
        label: 'Pod spacing',
        type: 'number',
        default: 0.3,
        min: 0.05,
        max: 0.5,
        step: 0.005,
        unit: 'm',
        display: 'in',
        advanced: true,
        help: 'Between the two parallel pods of a three-pod setup. The heading comes out of this number, so a 3 percent error here is a 3 percent error on every turn.',
      },
      {
        path: 'odometry.podRadius',
        label: 'Pod wheel radius',
        type: 'number',
        default: 0.024,
        min: 0.005,
        max: 0.06,
        step: 0.001,
        unit: 'm',
        display: 'in',
        advanced: true,
        help: 'goBILDA\u2019s 48 mm pod wheel is 24 mm. A radius 1 percent out is a distance 1 percent out, everywhere.',
      },
      {
        path: 'odometry.ticksPerRev',
        label: 'Pod ticks per revolution',
        type: 'number',
        default: 2000,
        min: 100,
        max: 16384,
        step: 1,
        advanced: true,
        help: '2000 for a goBILDA swingarm pod, 8192 for a REV through-bore. Sets how coarse the quantisation is.',
      },
      {
        path: 'odometry.quantise',
        label: 'Quantise pod counts',
        type: 'boolean',
        default: true,
        advanced: true,
        help: 'Round pod readings to whole ticks, as real hardware does. Because the pose is an integral, the rounding accumulates rather than averaging out.',
      },
    ],
  },

  {
    id: 'control',
    label: 'Control Hub',
    description:
      'How commands become motor output. Run mode and loop timing change the feel of the robot more than most teams expect.',
    params: [
      {
        path: 'control.runMode',
        label: 'Run mode',
        type: 'enum',
        options: [
          { value: 'RUN_WITHOUT_ENCODER', label: 'RUN_WITHOUT_ENCODER (open loop)' },
          { value: 'RUN_USING_ENCODER', label: 'RUN_USING_ENCODER (velocity PID)' },
        ],
        default: 'RUN_WITHOUT_ENCODER',
        help: 'Open loop sends the stick value straight out as duty cycle, so speed depends on battery and load. Velocity PID holds a commanded speed regardless, which tracks straighter but responds a touch more slowly.',
      },
      {
        path: 'control.zeroPowerBehavior',
        label: 'Zero power behavior',
        type: 'enum',
        options: [
          { value: 'BRAKE', label: 'BRAKE (shorted, resists motion)' },
          { value: 'FLOAT', label: 'FLOAT (open circuit, coasts)' },
        ],
        default: 'BRAKE',
        help: 'BRAKE shorts the motor so back-EMF stops the robot near where you release the stick. FLOAT lets it coast, which feels smoother but overshoots.',
      },
      {
        path: 'control.currentLimit',
        label: 'Per-motor current limit',
        type: 'number',
        default: 20,
        min: 2,
        max: 40,
        step: 0.5,
        unit: 'A',
        help: 'The REV Control Hub limits each port to 20 A. Lowering it reduces battery sag at the cost of acceleration.',
      },
      {
        path: 'control.hub.latency',
        label: 'Charge hub latency',
        type: 'boolean',
        default: true,
        help: 'Earn the loop rate instead of setting it. Every motor write, encoder read and I2C reading costs the time it costs on a real hub, and the total becomes the next cycle\u2019s period -- so code that talks to the hardware more runs slower, exactly as it does on the robot. Turn it off to go back to a fixed rate.',
      },
      {
        path: 'control.hub.cachingMode',
        label: 'Bulk caching',
        type: 'enum',
        options: [
          { value: 'AUTO', label: 'AUTO (one bulk read per pass)' },
          { value: 'MANUAL', label: 'MANUAL (until you clear it)' },
          { value: 'OFF', label: 'OFF (a read each)' },
        ],
        default: 'AUTO',
        help: 'LynxModule.BulkCachingMode. AUTO takes one bulk packet and expires it as soon as you read the same sensor twice. MANUAL keeps it until clearBulkCache(), which is faster and gives you stale readings the moment you forget the call. OFF makes every encoder reading its own hub round trip, which is the default a lot of teams never change.',
      },
      {
        path: 'control.loopOverheadMs',
        label: 'Loop overhead',
        type: 'number',
        default: 5,
        min: 0,
        max: 50,
        step: 0.5,
        suffix: 'ms',
        help: 'Everything in a cycle that is not a hub transaction: your own arithmetic, the telemetry packet to the Driver Station, the SDK\u2019s bookkeeping. Added to the charged hub time to get the loop period.',
      },
      {
        path: 'control.hub.writeMs',
        label: 'Cost of a write',
        type: 'number',
        default: 2.5,
        min: 0,
        max: 20,
        step: 0.1,
        suffix: 'ms',
        advanced: true,
        help: 'One motor power, servo position or run mode. This is the transaction most loops make most of.',
      },
      {
        path: 'control.hub.bulkReadMs',
        label: 'Cost of a bulk read',
        type: 'number',
        default: 2,
        min: 0,
        max: 20,
        step: 0.1,
        suffix: 'ms',
        advanced: true,
        help: 'One hub\u2019s worth of encoders, currents and digital inputs in a single packet.',
      },
      {
        path: 'control.hub.readMs',
        label: 'Cost of a single read',
        type: 'number',
        default: 2,
        min: 0,
        max: 20,
        step: 0.1,
        suffix: 'ms',
        advanced: true,
        help: 'A reading no bulk packet covers: battery voltage, a servo position, an analogue input.',
      },
      {
        path: 'control.hub.i2cMs',
        label: 'Cost of an I2C reading',
        type: 'number',
        default: 2.5,
        min: 0,
        max: 20,
        step: 0.1,
        suffix: 'ms',
        advanced: true,
        help: 'The built-in IMU, a colour sensor, a Pinpoint or an OTOS. I2C is the slow bus, and an IMU read in every loop is a real part of your cycle time.',
      },
      {
        path: 'control.loopRateHz',
        label: 'Fixed loop rate',
        type: 'number',
        default: 50,
        min: 5,
        max: 200,
        step: 1,
        unit: 'Hz',
        help: 'The rate used when hub latency is switched off. A typical FTC loop runs 30-60 Hz, and the robot cannot react faster than this no matter how quick the driver is.',
      },
      {
        path: 'control.inputLatencyMs',
        label: 'Input latency',
        type: 'number',
        default: 40,
        min: 0,
        max: 200,
        step: 1,
        suffix: 'ms',
        help: 'Gamepad poll, Driver Station, wifi, then the next loop cycle. Around 40 ms is realistic, and it is a large part of why a real robot feels less immediate than a naive simulator.',
      },
      {
        path: 'control.velocityLoop',
        label: 'Velocity loop',
        type: 'enum',
        options: [
          { value: 'hub', label: 'Hub emulation (ticks/sec, 16-bit duty)' },
          { value: 'normalised', label: 'Normalised (fraction of free speed)' },
        ],
        default: 'hub',
        help: 'Which arithmetic RUN_USING_ENCODER runs. Hub emulation is the loop that actually runs on a REV hub: ticks per second in, 16-bit duty out, I and D scaled by its own 20 Hz rate -- so the F, P and I you tuned in the SDK mean the same thing here. Normalised runs against velocity as a fraction of free speed, whose gains stay meaningful when the gearing changes.',
      },
      {
        path: 'control.hubPidfDefaults',
        label: 'SDK default coefficients',
        type: 'boolean',
        default: true,
        help: 'Derive F, P and I from the motor as the tuning guides do: F = 32767 / maxTicksPerSecond, P = 0.1F, I = 0.01F. Turn it off to type your own.',
      },
      {
        path: 'control.hubF',
        label: 'Hub F',
        type: 'number',
        default: 11.7,
        min: 0,
        max: 500,
        step: 0.1,
        advanced: true,
        help: 'Feedforward in the hub\u2019s units: duty out of 32767 per tick per second of target. 11.7 is right for a 312 RPM Yellow Jacket. Only used with the SDK defaults switched off.',
      },
      {
        path: 'control.hubP',
        label: 'Hub P',
        type: 'number',
        default: 1.17,
        min: 0,
        max: 200,
        step: 0.01,
        advanced: true,
        help: 'A tenth of F is the usual starting point. A drivetrain generally wants more.',
      },
      {
        path: 'control.hubI',
        label: 'Hub I',
        type: 'number',
        default: 0.117,
        min: 0,
        max: 50,
        step: 0.001,
        advanced: true,
        help: 'A hundredth of F is the usual starting point. A flywheel generally wants less -- the integral is what makes one overshoot after a shot.',
      },
      {
        path: 'control.hubD',
        label: 'Hub D',
        type: 'number',
        default: 0,
        min: 0,
        max: 50,
        step: 0.001,
        advanced: true,
        help: 'Almost always zero on a velocity loop: the measurement is a difference of quantised tick counts and differentiating it again amplifies the noise.',
      },
      {
        path: 'control.hub.velocityOverflow',
        label: '16-bit velocity overflow',
        type: 'boolean',
        default: true,
        advanced: true,
        help: 'The hub reports velocity as a signed 16-bit value in ticks per second, so past 32767 it wraps and reads large and negative. It only bites a fast shaft with a fine encoder -- which is exactly what a flywheel with a through-bore encoder is, and the reason a velocity loop on one can slam into reverse for no visible reason.',
      },
      {
        path: 'control.kP',
        label: 'Velocity kP',
        type: 'number',
        default: 1.5,
        min: 0,
        max: 20,
        step: 0.05,
        advanced: true,
        help: 'Gains are normalised: 1.0 means a full-scale velocity error commands full duty. Only used in RUN_USING_ENCODER.',
      },
      { path: 'control.kI', label: 'Velocity kI', type: 'number', default: 2.0, min: 0, max: 50, step: 0.1, advanced: true },
      { path: 'control.kD', label: 'Velocity kD', type: 'number', default: 0, min: 0, max: 5, step: 0.01, advanced: true },
      {
        path: 'control.kF',
        label: 'Velocity kF',
        type: 'number',
        default: 1.0,
        min: 0,
        max: 3,
        step: 0.01,
        advanced: true,
        help: 'Feedforward. 1.0 is the correct value for an ideal motor: full duty produces full speed.',
      },
      {
        path: 'control.encoderFilterHz',
        label: 'Encoder velocity filter',
        type: 'number',
        default: 20,
        min: 1,
        max: 200,
        step: 1,
        unit: 'Hz',
        advanced: true,
        help: 'Velocity is a difference of quantised tick counts, so it is far noisier than position. Lower cutoffs give a smoother signal at the cost of lag in the velocity loop.',
      },
      {
        path: 'control.quantiseEncoders',
        label: 'Quantise encoder counts',
        type: 'boolean',
        default: true,
        advanced: true,
        help: 'Round encoder readings to whole ticks, as real hardware does. Turn off to see how much of your velocity noise comes from quantisation.',
      },
    ],
  },

  {
    id: 'surface',
    label: 'Tiles & friction',
    description:
      'The contact model between wheels and the field. These are the numbers that decide whether the robot digs in or spins its wheels.',
    params: [
      {
        path: 'surface.model',
        label: 'Friction model',
        type: 'enum',
        options: [
          { value: 'pacejka', label: 'Pacejka (peak then slide)' },
          { value: 'tanh', label: 'Smooth saturating' },
          { value: 'linear', label: 'Linear saturating' },
        ],
        default: 'pacejka',
        help: 'Pacejka reproduces the drop from static to sliding grip, so breaking the wheels loose actually costs you. The other two saturate smoothly with no peak and are more forgiving numerically.',
      },
      {
        path: 'surface.muLongitudinal',
        label: 'Grip, rolling direction',
        type: 'number',
        default: 1.05,
        min: 0.1,
        max: 2,
        step: 0.01,
        help: 'Peak friction coefficient along the direction the wheel rolls. Rubber tread on clean FTC foam tiles is roughly 1.0-1.2; dusty tiles are noticeably less.',
      },
      {
        path: 'surface.muLateral',
        label: 'Grip, sideways',
        type: 'number',
        default: 1.0,
        min: 0.1,
        max: 2,
        step: 0.01,
        help: 'Peak friction across the wheel. Only affects traction wheels; roller wheels are free in their roller direction by construction.',
      },
      {
        path: 'surface.slipAtPeakGrip',
        label: 'Slip at peak grip',
        type: 'number',
        default: 0.15,
        min: 0.01,
        max: 1,
        step: 0.005,
        unit: 'm/s',
        advanced: true,
        help: 'How much sliding it takes to develop full grip. Smaller values make contact stiffer and the robot more responsive, but need a higher substep rate to stay stable.',
      },
      {
        path: 'surface.peakSlipRatio',
        label: 'Peak slip ratio',
        type: 'number',
        default: 0.12,
        min: 0,
        max: 0.5,
        step: 0.005,
        advanced: true,
        help: 'Above walking pace, peak grip moves to this fraction of rolling speed, which is how real tyres behave. Set to 0 for a pure slip-velocity model.',
      },
      {
        path: 'surface.kineticRatio',
        label: 'Sliding / peak grip',
        type: 'number',
        default: 0.8,
        min: 0.3,
        max: 0.99,
        step: 0.01,
        help: 'How much grip is left once a wheel has broken loose. 0.8 means spinning wheels give you 20% less force than wheels on the edge of grip, which is why easing into the throttle beats mashing it.',
      },
      {
        path: 'surface.curvature',
        label: 'Friction curve shape',
        type: 'number',
        default: 0.95,
        min: -1,
        max: 0.99,
        step: 0.01,
        advanced: true,
        help: 'Pacejka E. Shapes how sharply grip builds before the peak.',
      },
      {
        path: 'surface.rollingResistance',
        label: 'Rolling resistance',
        type: 'number',
        default: 0.02,
        min: 0,
        max: 0.15,
        step: 0.001,
        help: 'Deformation loss of the wheel in the foam, as a fraction of the load it carries. Foam tiles are much higher than a hard floor, which is why a robot coasts to a stop so quickly.',
      },
      {
        path: 'surface.rollerDrag',
        label: 'Roller drag (mecanum/omni)',
        type: 'number',
        default: 0.09,
        min: 0,
        max: 0.4,
        step: 0.005,
        help: 'Bearing friction and foam scrub along a roller\'s free direction. This is what makes strafing measurably slower and less efficient than driving straight.',
      },
    ],
  },

  {
    id: 'driver',
    label: 'Driver controls',
    description:
      'Everything between the stick and the drivetrain command. This is where most of the "feel" of a robot is decided, and the cheapest thing to experiment with.',
    params: [
      {
        path: 'driver.scheme',
        label: 'Drive scheme',
        type: 'enum',
        options: [
          { value: 'robotCentric', label: 'Robot centric (holonomic)' },
          { value: 'fieldCentric', label: 'Field centric (holonomic)' },
          { value: 'tank', label: 'Tank (two sticks)' },
          { value: 'arcade', label: 'Arcade (one stick)' },
          { value: 'splitArcade', label: 'Split arcade (throttle/turn separate)' },
        ],
        default: 'robotCentric',
        help: 'Robot centric means forward is wherever the robot is pointing. Field centric means forward is always away from the driver station, using the IMU.',
      },
      {
        path: 'driver.deadband',
        label: 'Stick deadband',
        type: 'number',
        default: 0.05,
        min: 0,
        max: 0.4,
        step: 0.005,
        help: 'Ignores small stick offsets so a worn controller does not creep. Values outside the band are rescaled so there is no jump at the edge.',
      },
      {
        path: 'driver.exponent',
        label: 'Response curve exponent',
        type: 'number',
        default: 2,
        min: 1,
        max: 4,
        step: 0.1,
        help: '1 is linear. 2 or 3 gives fine control near centre and full power at the ends, which most drivers prefer for precise alignment.',
      },
      {
        path: 'driver.curveBlend',
        label: 'Curve blend',
        type: 'number',
        default: 0.7,
        min: 0,
        max: 1,
        step: 0.01,
        help: 'Mixes between linear (0) and the full exponent curve (1). Around 0.7 keeps low-speed precision without feeling dead off centre.',
      },
      {
        path: 'driver.driveScale',
        label: 'Forward power limit',
        type: 'number',
        default: 1,
        min: 0.1,
        max: 1,
        step: 0.01,
        help: 'Caps forward/back power.',
      },
      {
        path: 'driver.strafeScale',
        label: 'Strafe power limit',
        type: 'number',
        default: 1,
        min: 0.1,
        max: 1.5,
        step: 0.01,
        help: 'Many teams push this above 1 to compensate for mecanum strafing being slower, then desaturation scales everything back down.',
      },
      {
        path: 'driver.turnScale',
        label: 'Turn power limit',
        type: 'number',
        default: 0.8,
        min: 0.1,
        max: 1,
        step: 0.01,
        help: 'Turning is usually the easiest axis to overdrive. Reducing it is the fastest fix for a robot that feels twitchy.',
      },
      {
        path: 'driver.slowModeFactor',
        label: 'Precision mode factor',
        type: 'number',
        default: 0.35,
        min: 0.05,
        max: 1,
        step: 0.01,
        help: 'Multiplier while the precision trigger is held. Used for scoring alignment.',
      },
      {
        path: 'driver.slewRate',
        label: 'Acceleration ramp',
        type: 'number',
        default: 6,
        min: 0.5,
        max: 60,
        step: 0.1,
        unit: '1/s',
        help: 'How fast commanded power may rise, in full-scale units per second. 6 means zero to full in about 170 ms. Lower values stop the driver from breaking the wheels loose, at the cost of responsiveness. Set high to disable.',
      },
      {
        path: 'driver.slewRateDown',
        label: 'Deceleration ramp',
        type: 'number',
        default: 30,
        min: 0.5,
        max: 100,
        step: 0.5,
        advanced: true,
        help: 'Separate ramp for reducing power. Keeping this fast means the robot still stops promptly even with a gentle acceleration ramp.',
      },
      {
        path: 'driver.turnSlewRate',
        label: 'Turn ramp',
        type: 'number',
        default: 10,
        min: 0.5,
        max: 100,
        step: 0.5,
        advanced: true,
        help: 'Separate ramp for the rotation axis.',
      },
      {
        path: 'driver.headingLockEnabled',
        label: 'Heading hold',
        type: 'boolean',
        default: false,
        help: 'When the driver is not commanding a turn, hold the current heading with a PD loop on the IMU. Stops the robot from being knocked off course, and makes strafing track straight.',
      },
      {
        path: 'driver.headingLockP',
        label: 'Heading hold kP',
        type: 'number',
        default: 2.5,
        min: 0,
        max: 20,
        step: 0.1,
        advanced: true,
      },
      {
        path: 'driver.headingLockD',
        label: 'Heading hold kD',
        type: 'number',
        default: 0.15,
        min: 0,
        max: 3,
        step: 0.01,
        advanced: true,
      },
      {
        path: 'driver.invertDrive',
        label: 'Invert forward axis',
        type: 'boolean',
        default: false,
        advanced: true,
      },
      {
        path: 'driver.invertTurn',
        label: 'Invert turn axis',
        type: 'boolean',
        default: false,
        advanced: true,
      },
    ],
  },

  {
    id: 'imu',
    label: 'IMU',
    description:
      'The heading sensor field-centric driving depends on. Its imperfections are modelled because they are the usual reason field-centric "stops working" mid-match.',
    params: [
      { path: 'imu.enabled', label: 'Simulate IMU error', type: 'boolean', default: true, help: 'Off gives a perfect heading, which is useful for telling an IMU problem apart from a driving problem.' },
      {
        path: 'imu.driftRateDegPerSec',
        label: 'Drift rate',
        type: 'number',
        default: 0.05,
        min: 0,
        max: 2,
        step: 0.01,
        suffix: 'deg/s',
        help: 'Accumulating bias. At 0.05 deg/s the heading is off by more than 7 degrees by the end of a two and a half minute match, which is enough to notice when strafing.',
      },
      { path: 'imu.noiseDeg', label: 'Angle noise', type: 'number', default: 0.05, min: 0, max: 2, step: 0.01, suffix: 'deg', advanced: true },
      { path: 'imu.latencySeconds', label: 'Read latency', type: 'number', default: 0.005, min: 0, max: 0.1, step: 0.001, unit: 's', advanced: true, help: 'I2C read delay inside the hub.' },
    ],
  },

  {
    id: 'field',
    label: 'Field',
    description: 'The 12 ft by 12 ft FTC field: foam tiles and a perimeter wall.',
    params: [
      {
        path: 'field.size',
        label: 'Field size',
        type: 'number',
        default: 144 * INCH,
        min: 60 * INCH,
        max: 200 * INCH,
        step: INCH,
        unit: 'm',
        display: 'in',
        help: 'Inside dimension of the perimeter. A competition field is 12 ft (144 in).',
      },
      {
        path: 'field.wallRestitution',
        label: 'Wall bounce',
        type: 'number',
        default: 0.15,
        min: 0,
        max: 0.8,
        step: 0.01,
        help: 'How much speed is returned on impact. FTC field walls are fairly dead; a robot mostly stops rather than bouncing.',
      },
      {
        path: 'field.wallFriction',
        label: 'Wall friction',
        type: 'number',
        default: 0.4,
        min: 0,
        max: 1.5,
        step: 0.01,
        help: 'Sliding friction along the wall. High values make a robot pinned against the wall hard to slide along it.',
      },
      {
        path: 'field.collisionsEnabled',
        label: 'Wall collisions',
        type: 'boolean',
        default: true,
      },
    ],
  },

  {
    id: 'sim',
    label: 'Simulation',
    description:
      'Solver settings. The defaults are chosen so the contact model stays stable; lower the substep rate only if you need the performance.',
    params: [
      {
        path: 'sim.substepHz',
        label: 'Physics substep rate',
        type: 'number',
        default: 2000,
        min: 250,
        max: 8000,
        step: 50,
        unit: 'Hz',
        help: 'Wheel contact is by far the stiffest part of the simulation. Too low and the robot jitters or the wheels oscillate; 2000 Hz is comfortable and costs very little.',
      },
      {
        path: 'sim.timeScale',
        label: 'Time scale',
        type: 'number',
        default: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        help: 'Slow motion for studying a manoeuvre, or to practise a sequence before running it at full speed.',
      },
      {
        path: 'sim.maxFrameSeconds',
        label: 'Max frame step',
        type: 'number',
        default: 0.05,
        min: 0.01,
        max: 0.25,
        step: 0.005,
        unit: 's',
        advanced: true,
        help: 'Caps how much simulated time one rendered frame may advance, so a stall in the browser cannot make the robot teleport.',
      },
    ],
  },

  {
    id: 'camera',
    label: 'Camera',
    description:
      'Where you are watching from. Drag with the mouse to look around and scroll to zoom in any view; those adjustments land here, so they persist and travel with an exported config.',
    params: [
      {
        path: 'view.camera',
        label: 'Camera',
        type: 'enum',
        options: [
          { value: 'driverStation', label: 'Driver station (match view)' },
          { value: 'chase', label: 'Chase' },
          { value: 'overhead', label: 'Overhead' },
          { value: 'orbit', label: 'Free orbit' },
        ],
        default: 'driverStation',
        help: 'Driver station is the view you actually have in a match: low, from one end, off to one side, with the far corners hard to judge. Press C to cycle.',
      },
      {
        path: 'view.fov',
        label: 'Field of view',
        type: 'number',
        default: 55,
        min: 18,
        max: 95,
        step: 1,
        suffix: 'deg',
        help: 'Narrower is more zoomed in. From the driver station the scroll wheel changes this, since you cannot walk onto the field.',
      },

      {
        path: 'view.driverHeight',
        label: 'Driver eye height',
        type: 'number',
        default: 1.55,
        min: 0.4,
        max: 3.5,
        step: 0.01,
        unit: 'm',
        display: 'in',
        help: 'How tall you are, standing. Shorter drivers genuinely find the far side of the field harder to read, and this reproduces that.',
      },
      {
        path: 'view.driverSetback',
        label: 'Distance behind wall',
        type: 'number',
        default: 1.1,
        min: 0.2,
        max: 4,
        step: 0.05,
        unit: 'm',
        display: 'in',
        help: 'How far back the driver station puts you from the field perimeter.',
      },
      {
        path: 'view.driverOffset',
        label: 'Position along the wall',
        type: 'number',
        default: 0,
        min: -2.2,
        max: 2.2,
        step: 0.02,
        unit: 'm',
        display: 'in',
        help: 'Negative is to your right as you face the field. Real alliance stations put you off to one side, which is why the far corner on your own side is the hardest place to judge distance.',
      },
      {
        path: 'view.driverAimDistance',
        label: 'Look-at distance',
        type: 'number',
        default: 2.6,
        min: 0.2,
        max: 8,
        step: 0.05,
        unit: 'm',
        display: 'in',
        advanced: true,
        help: 'How far down the field the camera is aimed. Larger values tip the view up toward the far wall.',
      },
      {
        path: 'view.driverAimHeight',
        label: 'Look-at height',
        type: 'number',
        default: 0.12,
        min: -0.5,
        max: 1.5,
        step: 0.01,
        unit: 'm',
        display: 'in',
        advanced: true,
      },
      {
        path: 'view.driverAimCentring',
        label: 'Aim centring',
        type: 'number',
        default: 0.7,
        min: 0,
        max: 1,
        step: 0.05,
        advanced: true,
        help: '0 looks straight down the field from wherever you stand; 1 always looks at the field centre line.',
      },

      {
        path: 'view.chaseDistance',
        label: 'Chase distance',
        type: 'number',
        default: 1.5,
        min: 0.5,
        max: 8,
        step: 0.05,
        unit: 'm',
        display: 'in',
      },
      {
        path: 'view.chaseHeight',
        label: 'Chase height',
        type: 'number',
        default: 0.95,
        min: 0.15,
        max: 4,
        step: 0.02,
        unit: 'm',
        display: 'in',
      },
      {
        path: 'view.chaseYaw',
        label: 'Chase angle',
        type: 'number',
        default: 0,
        min: -180,
        max: 180,
        step: 5,
        suffix: 'deg',
        advanced: true,
        help: '0 sits directly behind the robot. Swing it round to watch from the side while driving.',
      },
      {
        path: 'view.chaseAimHeight',
        label: 'Chase look-at height',
        type: 'number',
        default: 0.15,
        min: 0,
        max: 1,
        step: 0.01,
        unit: 'm',
        advanced: true,
      },
      {
        path: 'view.chaseSmoothing',
        label: 'Chase smoothing',
        type: 'number',
        default: 8,
        min: 0.5,
        max: 30,
        step: 0.5,
        advanced: true,
        help: 'Lower is lazier and less nauseating when the robot spins; higher sticks tightly to the robot.',
      },

      {
        path: 'view.overheadZoom',
        label: 'Overhead zoom',
        type: 'number',
        default: 1,
        min: 0.3,
        max: 4,
        step: 0.05,
        help: '1 frames the whole field.',
      },
      {
        path: 'view.overheadFollow',
        label: 'Overhead follows robot',
        type: 'boolean',
        default: false,
      },

      {
        path: 'view.orbitDistance',
        label: 'Orbit distance',
        type: 'number',
        default: 5.5,
        min: 0.6,
        max: 30,
        step: 0.1,
        unit: 'm',
        display: 'in',
      },
      {
        path: 'view.orbitPitch',
        label: 'Orbit elevation',
        type: 'number',
        default: 48,
        min: 2,
        max: 88,
        step: 1,
        suffix: 'deg',
      },
      {
        path: 'view.orbitYaw',
        label: 'Orbit rotation',
        type: 'number',
        default: -90,
        min: -180,
        max: 180,
        step: 1,
        suffix: 'deg',
      },
      {
        path: 'view.orbitFollow',
        label: 'Orbit follows robot',
        type: 'boolean',
        default: true,
        help: 'Keeps the robot centred while you orbit around it. Turn off, or pan with the right mouse button, to inspect a fixed part of the field.',
      },
    ],
  },

  {
    id: 'match',
    label: 'Match',
    description:
      'The BIOBUZZ MATCH itself. The defaults are the manual\'s (Section 10.1): a 30-second AUTO, an 8-second transition, a 2-minute TELEOP, and the FLOWERS opening with 60 seconds left. Change them to drill a part of the MATCH rather than sitting through all of it -- a 30-second TELEOP with the FLOWERS already open is the endgame, over and over.',
    params: [
      {
        path: 'match.alliance',
        label: 'Your alliance',
        type: 'enum',
        options: [
          { value: 'red', label: 'Red' },
          { value: 'blue', label: 'Blue' },
        ],
        default: 'red',
        help: 'Which side you drive for. Changing it re-stages the MATCH: your HIVE, your GARDEN and your LOADING ZONE all swap. Worth practising both, because the two are not mirror images to drive -- the raised CELL starts on the opposite end of the arm.',
      },
      {
        path: 'match.startPhase',
        label: 'Start the match in',
        type: 'enum',
        options: [
          { value: 'auto', label: 'Autonomous (full match)' },
          { value: 'teleop', label: 'Driver control (skip auto)' },
        ],
        default: 'auto',
        help: 'Skipping AUTO puts you straight on the sticks. The AUTO period still counts as having happened -- LEAVE and AUTO PARK simply go unscored -- so the score reads the way it would after an AUTO where nothing moved.',
      },
      {
        path: 'match.autoRestart',
        label: 'Restart when the match ends',
        type: 'boolean',
        default: false,
        help: 'Goes back to setup and starts again a couple of seconds after the buzzer, so a practice session is one long loop instead of a key press between every match.',
      },
      {
        path: 'match.autoSeconds',
        label: 'Autonomous length',
        type: 'number',
        default: 30,
        min: 0,
        max: 60,
        step: 1,
        unit: 's',
      },
      {
        path: 'match.transitionSeconds',
        label: 'Transition length',
        type: 'number',
        default: 8,
        min: 0,
        max: 30,
        step: 1,
        unit: 's',
        advanced: true,
      },
      {
        path: 'match.teleopSeconds',
        label: 'Driver control length',
        type: 'number',
        default: 120,
        min: 10,
        max: 300,
        step: 5,
        unit: 's',
      },
      {
        path: 'match.flowerUnlockRemaining',
        label: 'FLOWERS open with',
        type: 'number',
        default: 60,
        min: 0,
        max: 300,
        step: 5,
        unit: 's',
        help: 'G410: NECTAR may not enter a FLOWER until this much time is left, and at that point an ALLIANCE may enter all of its remaining NECTAR. Set it to the whole TELEOP length to have the FLOWERS open from the start; set it to 0 to keep them shut.',
      },
      {
        path: 'match.launchSystem',
        label: 'Your launch system',
        type: 'enum',
        options: LAUNCH_SYSTEM_OPTIONS,
        default: 'flywheel',
        help: 'How your ROBOT gets an element into a CELL. This changes what you are practising, not just how well it works: a flywheel makes you wait for the wheel and punishes firing early, a catapult has no early to fire at but a fixed reset and a hard maximum range, and a puncher only reaches from close in. Takes effect on the next MATCH (M).',
      },
      {
        path: 'match.aiDriveTeam',
        label: 'Other side enters its NECTAR',
        type: 'boolean',
        default: true,
        help: 'Entering NECTAR is a human action, so somebody has to do it for the opposing ALLIANCE or a third of the point table never happens: no NECTAR on the FIELD means no FLOWER can be owned, because ownership is the top-most NECTAR and POLLEN confers none. Your own ALLIANCE\'s NECTAR stays yours to enter -- when to hand it in is a real decision, and handing it in early is a G410 violation.',
      },
      {
        path: 'match.moveTolerance',
        label: 'Shot drift tolerance',
        type: 'number',
        default: 0.35,
        min: 0.05,
        max: 2,
        step: 0.05,
        unit: 'm/s',
        advanced: true,
        help: 'How fast the ROBOT may be moving before the panel tells you to stop before shooting. It does not change the physics -- a shot always inherits the ROBOT\'s velocity -- only the point at which the prompt starts warning you.',
      },
      {
        path: 'match.sortElements',
        label: 'Intake rejects opponent NECTAR',
        type: 'boolean',
        default: true,
        help: 'G408 forbids CONTROLLING the opponent\'s NECTAR, and it is worth nothing to you anyway, so most ROBOTS sense the colour and refuse it. On, the intake drives straight over one. Off, it swallows whatever enters -- which is what a ROBOT with no colour sensor does, and then it is on you to steer around them or take the warning.',
      },
    ],
  },

  {
    id: 'shooter',
    label: 'Shooter',
    description:
      "Your launcher, in the numbers a team would measure on their own. The defaults are a single bare 5202 direct-driving a 4 in wheel with a deliberate flywheel mass on it, which reaches 2400 rpm in about two seconds and idles at 0.8 A. Anything you leave alone here comes from the launch system chosen under Match; anything you move overrides it, so pick the system first and then dial it toward your robot.\n\nNothing constrains when you can fire. The ball leaves at whatever surface speed the wheel is actually doing, so pulling the trigger early throws it short -- which is the whole point of the recovery bar.",
    params: [
      {
        path: 'shooter.motorCount',
        label: 'Motors on the wheel',
        type: 'number',
        default: 1,
        min: 1,
        max: 4,
        step: 1,
        help: 'The single biggest lever on recovery time. Two motors put back twice the angular momentum per second, so a two-motor shooter can fire as fast as its feeder.',
      },
      {
        path: 'shooter.inertia',
        label: 'Flywheel inertia',
        type: 'number',
        default: 8.3e-4,
        min: 5e-5,
        max: 6e-3,
        step: 5e-5,
        suffix: 'kg m^2',
        help: 'A bare 4 in compliant wheel is only about 1e-4, which loses a third of its speed to every ball -- which is why shooters get a flywheel mass bolted to them. More inertia means slower spin-up and far better recovery, and that trade is the whole design of a shooter.',
      },
      {
        path: 'shooter.wheelRadius',
        label: 'Wheel radius',
        type: 'number',
        default: 2 * INCH,
        min: 0.75 * INCH,
        max: 4 * INCH,
        step: 0.125 * INCH,
        unit: 'm',
        display: 'in',
        help: 'Exit speed is the surface speed times the transfer, so a bigger wheel needs less RPM for the same range -- and takes a bigger hit from every ball, because the ball has more leverage on it.',
      },
      {
        path: 'shooter.gearRatio',
        label: 'Gear ratio to the wheel',
        type: 'number',
        default: 1,
        min: 0.25,
        max: 4,
        step: 0.05,
        help: 'Above 1 the wheel spins faster than the motor. Gearing up buys surface speed and throws away torque, so it spins up slower and recovers worse; the rotor inertia it reflects to the wheel also shrinks as the square of this.',
        advanced: true,
      },
      {
        path: 'shooter.transferEfficiency',
        label: 'Transfer to the ball',
        type: 'number',
        default: 0.5,
        min: 0.2,
        max: 1,
        step: 0.02,
        help: 'The fraction of surface speed the ball leaves at. One wheel against a fixed backplate spends part of the contact spinning the ball up, so a real one lands near 0.5; two counter-rotating wheels grip from both sides and get close to 0.9. It is also how much the wheel loses per shot, so it cuts both ways.',
      },
      {
        path: 'shooter.drag',
        label: 'Wheel drag',
        type: 'number',
        default: 8e-5,
        min: 0,
        max: 5e-4,
        step: 1e-5,
        suffix: 'N m / rad/s',
        help: 'Bearings, windage and hysteresis in the tread, lumped together. Calibrated against the number you can actually read on a Driver Station: this puts a single 5202 at about 0.8 A holding 2400 rpm.',
        advanced: true,
      },
      {
        path: 'shooter.targetRpm',
        label: 'Target RPM',
        type: 'number',
        default: 2400,
        min: 200,
        max: 6000,
        step: 50,
        suffix: 'rpm',
        help: 'What the velocity loop holds. The aiming solver overwrites it whenever you aim at the HIVE, so this is the starting point and the number the d-pad trims.',
      },
      {
        path: 'shooter.readyTolerance',
        label: 'Ready threshold',
        type: 'number',
        default: 0.97,
        min: 0.5,
        max: 1,
        step: 0.01,
        help: 'How close to target counts as READY on the panel. Advisory only -- it has never stopped you firing, and now it visibly does not.',
        advanced: true,
      },
      {
        path: 'shooter.feedInterval',
        label: 'Feeder interval',
        type: 'number',
        default: 0.35,
        min: 0.05,
        max: 2,
        step: 0.05,
        unit: 's',
        help: 'The shortest time between shots the feeder can manage. With a two-motor shooter this, rather than the wheel, is usually what limits your cycle.',
      },
      {
        path: 'shooter.hoodScatter',
        label: 'Hood repeatability',
        type: 'number',
        default: 0,
        min: 0,
        max: 4,
        step: 0.1,
        suffix: 'deg',
        help: 'Shot-to-shot spread on the release angle. Zero by default, so a missed shot is yours -- put a real number in if your hood moves when you look at it, and the AI robots already carry one from their build quality.',
        advanced: true,
      },
      {
        path: 'shooter.rpmScatter',
        label: 'Speed repeatability',
        type: 'number',
        default: 0,
        min: 0,
        max: 0.12,
        step: 0.005,
        help: 'Shot-to-shot spread on exit speed, as a fraction.',
        advanced: true,
      },
    ],
  },

  {
    id: 'ai',
    label: 'The other three robots',
    description:
      'A MATCH is four ROBOTS: you, a partner, and two opponents. Each of the other three is a real simulated robot -- same physics, same motors, same battery, same mechanisms, driven through the same subsystem calls you are -- so beating one is a driving result and not a difficulty setting. Pick what each one is, how well it is built and who is driving it, or leave any of it on Random for a different MATCH every time.',
    params: [
      {
        path: 'ai.enabled',
        label: 'Fill the other three seats',
        type: 'boolean',
        default: false,
        help: 'Off gives you an empty FIELD to learn the cycle on. On is a real MATCH, and much harder -- there are three other robots in the way and the POLLEN runs out.',
      },
      ...ROSTER_SLOTS.flatMap(rosterParams),
    ],
  },

  {
    id: 'view',
    label: 'Overlays',
    description: 'Debug rendering and telemetry. None of this affects the physics.',
    params: [
      { path: 'view.showForceVectors', label: 'Wheel force vectors', type: 'boolean', default: true, help: 'Green is grip in reserve, red means that wheel is at the limit and sliding.' },
      { path: 'view.showSlip', label: 'Slip markers', type: 'boolean', default: true },
      { path: 'view.showTrail', label: 'Path trail', type: 'boolean', default: true },
      {
        path: 'view.showAprilTags',
        label: 'AprilTags',
        type: 'boolean',
        default: true,
        help: 'Outline the sixteen tags where they actually are, and light up the ones the camera can currently read. The quickest way to see why a tag on the underside of a raised CELL is hard to find.',
      },
      {
        path: 'view.showGamepad',
        label: 'On-screen gamepad',
        type: 'boolean',
        default: true,
        help: 'Draw the sticks, triggers and buttons as the simulator sees them. Two dots per stick: the solid one is what your op-mode is being given, the faint one is what the controller is reporting right now, and the gap between them is the input delay. Also the quickest way to find out that an F310 is on the wrong mode.',
      },
      {
        path: 'view.showDrawings',
        label: 'Routine drawings',
        type: 'boolean',
        default: true,
        help: 'Show what a pasted AUTO routine draws with robot.draw -- its targets, its planned path, its waypoints. The hard part of debugging an AUTO is not what the robot did but what the routine believed, and a cross on the tiles says that better than three decimals on a panel.',
      },
      {
        path: 'view.showOdometryTrail',
        label: 'Odometry trail',
        type: 'boolean',
        default: true,
        help: 'Draw where the odometry thinks the robot went, alongside where it actually went. The gap between the two lines is the drift, and watching it open up over a lap of the field is the fastest way to understand why an AUTO that works twice fails the third time.',
      },
      { path: 'view.showLoads', label: 'Wheel load rings', type: 'boolean', default: false, help: 'Ring size shows how much weight each wheel is carrying right now.' },
      { path: 'view.showHud', label: 'Telemetry HUD', type: 'boolean', default: true },
      { path: 'view.showGraphs', label: 'Telemetry graphs', type: 'boolean', default: true },
      { path: 'view.showChallengeLabels', label: 'Challenge labels', type: 'boolean', default: true, help: 'Numbers and distances drawn over gates and targets during a drill.' },
      { path: 'view.showTrajectory', label: 'Shot trajectory guide', type: 'boolean', default: false, help: 'Draws the arc the ball would actually fly on the current hood angle and wheel speed, and marks where it crosses the CELL\'s opening plane. Off by default: aiming by eye is the skill, and the guide is for learning what the numbers mean. Key T.' },
      { path: 'view.trajectoryMode', label: 'Trajectory shows', type: 'enum', default: 'live', options: [{ value: 'live', label: 'Actual shot (current RPM)' }, { value: 'solution', label: 'Solved shot (needed RPM)' }, { value: 'both', label: 'Both' }], help: 'The actual arc tells you where this shot goes. The solved arc tells you where a correct one would go, so firing early shows you the gap.' },
      { path: 'view.trailSeconds', label: 'Trail length', type: 'number', default: 6, min: 1, max: 30, step: 1, unit: 's', advanced: true },
    ],
  },
];

/** Flat list of every parameter, for lookups. */
export const ALL_PARAMS = SCHEMA.flatMap((g) => g.params);

/** @type {Map<string, ParamDef>} */
export const PARAM_BY_PATH = new Map(ALL_PARAMS.map((p) => [p.path, p]));

/**
 * Build the nested defaults object from the schema.
 * @returns {SimConfig}
 */
export function defaultConfig() {
  /** @type {any} */
  const out = {};
  for (const param of ALL_PARAMS) {
    const parts = param.path.split('.');
    let node = out;
    for (let i = 0; i < parts.length - 1; i++) {
      node[parts[i]] ??= {};
      node = node[parts[i]];
    }
    node[parts[parts.length - 1]] = param.default;
  }
  // Values not exposed as tunables but needed by the model.
  out.motor.name = MOTOR_PRESETS[DEFAULT_MOTOR_ID].name;
  return out;
}

/**
 * The shape produced by `defaultConfig`. Declared loosely on purpose: the
 * schema is the authority, and this typedef exists so editors can autocomplete.
 * @typedef {ReturnType<typeof defaultConfig> & Record<string, any>} SimConfig
 */
