#!/usr/bin/env node
/**
 * Write `docs/RULES.md` from `src/field/biobuzz/rules.js`.
 *
 * Generated rather than hand-written, because a hand-written audit is out of
 * date the first time somebody adds a detector and forgets the document. The
 * catalogue is the source of truth, a test checks it against the manual's own
 * list of forty rules, and this turns it into something readable.
 *
 * Usage: node tools/rules-doc.js [--check]
 *   --check  fail instead of writing, for CI
 */
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PENALTY_POINTS, RULES } from '../src/field/biobuzz/rules.js';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const OUT = resolve(ROOT, 'docs/RULES.md');

/** Section headings, in the order they are worth reading. */
const SECTIONS = [
  [
    'live',
    'Officiated during a MATCH',
    'The REFEREE watches for these every step and assesses the manual’s own penalty. ' +
      'This is where the practice value is: a MAJOR FOUL is ' +
      `${PENALTY_POINTS.major} points, which is ten elements in a CELL.`,
  ],
  [
    'advisory',
    'Detected and reported, never scored',
    'The sim can see something that looks like this, but the manual’s test is whether a ' +
      'REFEREE judged the action STRATEGIC. Shown to the driver with no points attached -- ' +
      'putting a foul on a heuristic teaches people to avoid the heuristic.',
  ],
  [
    'setup',
    'Checked before the MATCH',
    'Staging, rather than play.',
  ],
  [
    'structural',
    'Cannot be violated here',
    'Each of these names the mechanism that makes it impossible, so the claim can be ' +
      'checked rather than taken on trust.',
  ],
  [
    'unmodeled',
    'Not modelled',
    'A real ROBOT could violate these and this one cannot, because the physics has no ' +
      'model for what the rule is about. Damage and tipping over are the whole list.',
  ],
  [
    'human',
    'DRIVE TEAM conduct',
    'There are no humans in the sim beyond the one hand that rolls NECTAR into the ' +
      'LOADING ZONE, so there is nothing to watch.',
  ],
  [
    'event',
    'Event logistics',
    'Decided outside a single MATCH: queueing, inspection, the Head REFEREE.',
  ],
];

function table(rules) {
  const rows = [
    '| Rule | | Violation | What the sim does |',
    '| --- | --- | --- | --- |',
  ];
  for (const r of rules) {
    const note = r.note.replace(/\|/g, '\\|').replace(/\n/g, ' ');
    rows.push(`| **${r.id}** | ${r.title} | ${r.penalty} | ${note} |`);
  }
  return rows.join('\n');
}

function render() {
  const counts = Object.fromEntries(
    SECTIONS.map(([key]) => [key, RULES.filter((r) => r.coverage === key).length]),
  );
  const lines = [];
  lines.push('# BIOBUZZ rules: what the simulator enforces');
  lines.push('');
  lines.push(
    '<!-- Generated by `node tools/rules-doc.js` from src/field/biobuzz/rules.js.',
    '     Edit the catalogue, not this file. -->',
  );
  lines.push('');
  lines.push(
    'All forty Game Rules from the BIOBUZZ V1 manual, and what this simulator does about',
    'each one. The point of listing the ones it cannot check is that the gaps are then',
    'visible: a rule missing from a list is a surprise at an event, and a rule marked',
    '"cannot be violated here" is a known limit.',
  );
  lines.push('');
  lines.push(
    `Of the forty: **${counts.live} are officiated live**, ${counts.advisory} is detected and`,
    `reported without being scored, ${counts.setup} is checked at setup,`,
    `${counts.structural} cannot happen here, ${counts.unmodeled} are outside the physics,`,
    `and ${counts.human + counts.event} are about people and events rather than ROBOTS.`,
  );
  lines.push('');
  lines.push('## Penalties (Table 10-4)');
  lines.push('');
  lines.push(
    `A MINOR FOUL is a credit of **${PENALTY_POINTS.minor} points** and a MAJOR FOUL a credit`,
    `of **${PENALTY_POINTS.major} points** "towards the opponent’s MATCH point total". That`,
    'wording matters and the score follows it: a foul you commit is added to the other',
    'ALLIANCE’S total, it is not deducted from yours, so a foul can never take you below',
    'the points you earned. In the panel it is the PENALTY row, and it reads as points',
    'gained from the opponent’s fouls.',
  );
  lines.push('');
  lines.push('## STRATEGIC, without reading minds');
  lines.push('');
  lines.push(
    'A dozen rules read "VERBAL WARNING. MAJOR FOUL and YELLOW CARD, if STRATEGIC", and',
    'STRATEGIC is a REFEREE’S judgement of intent. Section 10.6 says how that judgement',
    'is reached, though: "multiple warnings are given during an individual MATCH for the',
    'same violation that individually can be perceived to be accidental". So that is the',
    'model -- the first instances draw a warning, and a repeat inside the same MATCH is',
    'STRATEGIC and takes the foul. It is the manual’s own test, and it is the right',
    'lesson anyway: doing it once is forgivable, doing it repeatedly is not.',
  );
  lines.push('');
  for (const [key, heading, blurb] of SECTIONS) {
    const rules = RULES.filter((r) => r.coverage === key);
    if (rules.length === 0) continue;
    lines.push(`## ${heading} (${rules.length})`);
    lines.push('');
    lines.push(blurb);
    lines.push('');
    lines.push(table(rules));
    lines.push('');
  }
  lines.push('## Where this lives in the code');
  lines.push('');
  lines.push(
    '- `src/field/biobuzz/rules.js` -- the catalogue above, and the penalty values.',
    '- `src/field/biobuzz/Referee.js` -- the detectors for the live rules.',
    '- `src/field/biobuzz/Match.js` -- owns the REFEREE and folds the penalty into the score.',
    '- `src/field/biobuzz/BiobuzzField.js` -- Section 10.8.2, returning elements that left.',
    '- `test/biobuzz-rules.test.js` -- checks the list against the manual and every detector.',
  );
  lines.push('');
  return lines.join('\n');
}

const text = render();
if (process.argv.includes('--check')) {
  const existing = await readFile(OUT, 'utf8').catch(() => '');
  if (existing !== text) {
    console.error('docs/RULES.md is stale -- run `node tools/rules-doc.js`');
    process.exit(1);
  }
  console.log('docs/RULES.md is up to date');
} else {
  await writeFile(OUT, text);
  console.log(`wrote ${OUT}`);
}
